/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.CIT260.DaenirisTheForgotten.Frames;

import byui.CIT260.DaenirisTheForgotten.Control.BattleControl;
import byui.CIT260.DaenirisTheForgotten.Control.Constants;
import byui.CIT260.DaenirisTheForgotten.Control.SpellControl;
import byui.CIT260.DaenirisTheForgotten.Model.BattleScene;
import byui.CIT260.DaenirisTheForgotten.Model.Game;
import byui.CIT260.DaenirisTheForgotten.Model.Spells;
import daeniristheforgotten.DaenirisTheForgotten;

/**
 *
 * @author Joshua
 */


public class BattleFrame extends javax.swing.JFrame {
    Game game = DaenirisTheForgotten.currentGame;
    AdventureMenuFrame adventureMenuFrame = null;
    BattleScene data = game.getBattle();
    
    public BattleFrame(AdventureMenuFrame adventureMenuFrame){
        this();
        this.adventureMenuFrame = adventureMenuFrame;
    }


    public BattleFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.playerInfo.setText("Name " + data.getName()
                                +"\nHealth " + data.getCurrentHealth() + "/" + data.getTotalHealth()
                                +"\nMagic " + data.getCurrentMagic() + "/" + data.getTotalMagic());
        this.enemyInfo.setText("Name " + data.getEnemyName()
                                +"\nHealth " + data.getEnemyCurrentHealth() + "/" + data.getEnemyHealth()
                                +"\nMagic " + data.getEnemyCurrentMagic() + "/" + data.getEnemyMagic());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        attackButton = new javax.swing.JButton();
        defendButton = new javax.swing.JButton();
        magicButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        battleText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        enemyInfo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        enemyBattleText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        attackButton.setText("Attack");
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        defendButton.setText("Defend");
        defendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defendButtonActionPerformed(evt);
            }
        });

        magicButton.setText("Magic");
        magicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magicButtonActionPerformed(evt);
            }
        });

        itemButton.setText("Item");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        playerInfo.setColumns(20);
        playerInfo.setRows(5);
        jScrollPane1.setViewportView(playerInfo);

        battleText.setColumns(20);
        battleText.setRows(5);
        jScrollPane2.setViewportView(battleText);

        enemyInfo.setColumns(20);
        enemyInfo.setRows(5);
        jScrollPane3.setViewportView(enemyInfo);

        enemyBattleText.setColumns(20);
        enemyBattleText.setRows(5);
        jScrollPane4.setViewportView(enemyBattleText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemButton)
                    .addComponent(runButton)
                    .addComponent(attackButton)
                    .addComponent(defendButton)
                    .addComponent(magicButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(attackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(defendButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(magicButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(itemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(runButton))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed

        if(BattleControl.hit()){
            this.battleText.setText(BattleControl.attackEnemy());   
        }
        else{
            this.battleText.setText("Your attack missed the enemy");
        }
        
        endTurn();
    }//GEN-LAST:event_attackButtonActionPerformed

    private void defendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defendButtonActionPerformed
        this.battleText.setText("\n\tYour defense increased by " + BattleControl.defend1() + " temporarily");
        this.enemyBattleText.setText(BattleControl.enemyAttack());
        
        endTurn();
        
        BattleControl.defend2();
    }//GEN-LAST:event_defendButtonActionPerformed

    private void magicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magicButtonActionPerformed
        MagicMenuFrame spell = new MagicMenuFrame(this, true);
        spell.setVisible(true);
    }//GEN-LAST:event_magicButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        ItemsMenuFrame itemsMenu = new ItemsMenuFrame(this, true);
        itemsMenu.setVisible(true);
        this.enemyBattleText.setText(BattleControl.enemyAttack());
    }//GEN-LAST:event_itemButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        String run = BattleControl.run1();
            if(run == "You successfully ran from the enemy"){
            SuccessfulRunFrame ran = new SuccessfulRunFrame();
            ran.setVisible(true);
            this.dispose();
            }
            else{
            this.battleText.setText("You were unable to run from the enemy");
            this.enemyBattleText.setText(BattleControl.enemyAttack());
            }
    }//GEN-LAST:event_runButtonActionPerformed
    
    public void endTurn(){
        if(BattleControl.checkEnemyDeath()){
            BattleWonFrame battleWon = new BattleWonFrame(this.adventureMenuFrame);
            battleWon.setVisible(true);
            this.dispose();
        }
        
        this.enemyBattleText.setText(BattleControl.enemyAttack());
        if(BattleControl.playerDead()){
            if(data.isPheonix()){
                SpellControl.pheonix();
                data.setPheonix(false);
            }
            else{
                GameOver gameOver = new GameOver();
                gameOver.setVisible(true);
                this.dispose();
            }
            
        }
        this.playerInfo.setText("Name " + data.getName()
                                +"\nHealth " + data.getCurrentHealth() + "/" + data.getTotalHealth()
                                +"\nMagic " + data.getCurrentMagic() + "/" + data.getTotalMagic());
        this.enemyInfo.setText("Name " + data.getEnemyName()
                                +"\nHealth " + data.getEnemyCurrentHealth() + "/" + data.getEnemyHealth()
                                +"\nMagic " + data.getEnemyCurrentMagic() + "/" + data.getEnemyMagic());
    }
    
    public void magicResults(Spells spell){
        
        if (spell.getSpellType() == Constants.SPELL_ATTACK_HEALTH){
            this.battleText.setText("\n" + spell.getMessage() + "\n"
                             + spell.getSpecialEffects()
                             + " damage to the enemy.");
        }
        else if (spell.getSpellType() == Constants.SPELL_HEAL_HEALTH){
            this.battleText.setText("\n" + spell.getMessage() + "\n"
                             + spell.getSpecialEffects()
                             + " points.");
        }
        else{
            this.battleText.setText("\n" + spell.getMessage() + "\n"
                             + spell.getSpecialEffects()
                             + "%");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackButton;
    private javax.swing.JTextArea battleText;
    private javax.swing.JButton defendButton;
    private javax.swing.JTextArea enemyBattleText;
    private javax.swing.JTextArea enemyInfo;
    private javax.swing.JButton itemButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton magicButton;
    private javax.swing.JTextArea playerInfo;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
