/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.CIT260.DaenirisTheForgotten.Frames;

import byui.CIT260.DaenirisTheForgotten.Control.PCStatsControl;
import byui.CIT260.DaenirisTheForgotten.Model.Actor;
import byui.CIT260.DaenirisTheForgotten.Model.Game;
import byui.CIT260.DaenirisTheForgotten.Model.PlayerCharacter;
import daeniristheforgotten.DaenirisTheForgotten;

/**
 *
 * @author Joshua
 */
public class DistributeBonuses extends javax.swing.JFrame {
        Game game = DaenirisTheForgotten.getCurrentGame();
        Actor[][] actor = game.getActor();
        PlayerCharacter player = ((PlayerCharacter) actor[0][0]);
        AdventureMenuFrame adventureMenuFrame;
        boolean newGame = true;

    /**
     * Creates new form DistributeBonuses
     * @param adventureMenuFrame
     */

    public DistributeBonuses(AdventureMenuFrame adventureMenu){
        this();
        this.adventureMenuFrame = adventureMenu;
        this.newGame = false;
    }
    public DistributeBonuses() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.playerStats.setText(player.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerInfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bonusesDisplay = new javax.swing.JLabel();
        attackUp = new javax.swing.JButton();
        defenseUp = new javax.swing.JButton();
        mAttackUp = new javax.swing.JButton();
        mDefenseUp = new javax.swing.JButton();
        hPUp = new javax.swing.JButton();
        mPUp = new javax.swing.JButton();
        resetPointsButton = new javax.swing.JButton();
        finishedButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerStats = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        bonusesDisplay.setText("Please Distribute your bonuses");

        attackUp.setText("Attack");
        attackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackUpActionPerformed(evt);
            }
        });

        defenseUp.setText("Defense");
        defenseUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defenseUpActionPerformed(evt);
            }
        });

        mAttackUp.setText("Magic Attack");
        mAttackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAttackUpActionPerformed(evt);
            }
        });

        mDefenseUp.setText("Magic Defense");
        mDefenseUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDefenseUpActionPerformed(evt);
            }
        });

        hPUp.setText("Health Points (5)");
        hPUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hPUpActionPerformed(evt);
            }
        });

        mPUp.setText("Magic Points (5)");
        mPUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPUpActionPerformed(evt);
            }
        });

        resetPointsButton.setText("Reset Points");
        resetPointsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPointsButtonActionPerformed(evt);
            }
        });

        finishedButton.setText("Finished");
        finishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedButtonActionPerformed(evt);
            }
        });

        playerStats.setColumns(20);
        playerStats.setRows(5);
        jScrollPane1.setViewportView(playerStats);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bonusesDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hPUp)
                            .addComponent(mPUp)
                            .addComponent(mAttackUp)
                            .addComponent(mDefenseUp)
                            .addComponent(attackUp)
                            .addComponent(defenseUp))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetPointsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishedButton)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bonusesDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(attackUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defenseUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mAttackUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mDefenseUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hPUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPUp)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPointsButton)
                    .addComponent(finishedButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackUpActionPerformed
        PCStatsControl.attackUp(player);
        this.playerStats.setText(player.toString());
    }//GEN-LAST:event_attackUpActionPerformed

    private void defenseUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenseUpActionPerformed
        PCStatsControl.defenseUp(player);
        this.playerStats.setText(player.toString());
    }//GEN-LAST:event_defenseUpActionPerformed

    private void mAttackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAttackUpActionPerformed
                PCStatsControl.mAttackUp(player);
                this.playerStats.setText(player.toString());
    }//GEN-LAST:event_mAttackUpActionPerformed

    private void mDefenseUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDefenseUpActionPerformed
                PCStatsControl.mDefenseUp(player);
                this.playerStats.setText(player.toString());
    }//GEN-LAST:event_mDefenseUpActionPerformed

    private void hPUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hPUpActionPerformed
                PCStatsControl.HPUp(player);
                this.playerStats.setText(player.toString());
    }//GEN-LAST:event_hPUpActionPerformed

    private void mPUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPUpActionPerformed
                PCStatsControl.MPUp(player);
                this.playerStats.setText(player.toString());
    }//GEN-LAST:event_mPUpActionPerformed

    private void resetPointsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPointsButtonActionPerformed
                PCStatsControl.resetPoints(player);
                this.playerStats.setText(player.toString());
    }//GEN-LAST:event_resetPointsButtonActionPerformed

    private void finishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedButtonActionPerformed
        

        if (!newGame){
            this.dispose();
            return;
        }
        
        AdventureMenuFrame adventureMenu = new AdventureMenuFrame();
        adventureMenu.setVisible(true);
        
        
        this.dispose();
    }//GEN-LAST:event_finishedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributeBonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributeBonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributeBonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributeBonuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributeBonuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackUp;
    private javax.swing.JLabel bonusesDisplay;
    private javax.swing.JButton defenseUp;
    private javax.swing.JButton finishedButton;
    private javax.swing.JButton hPUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAttackUp;
    private javax.swing.JButton mDefenseUp;
    private javax.swing.JButton mPUp;
    private javax.swing.JLabel playerInfo;
    private javax.swing.JTextArea playerStats;
    private javax.swing.JButton resetPointsButton;
    // End of variables declaration//GEN-END:variables
}
